/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.Arkiva;
import DAL.ArkivaException;
import DAL.ArkivaInterface;
import DAL.ArkivaRepository;
import DAL.ProfesoriInterface;
import DAL.ProfesoriRepository;
import Model.ArkivaTableModel;
import java.awt.Desktop;
import java.awt.Dimension;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import static java.lang.Character.isDigit;
import java.nio.file.Files;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author Arbër Suka
 */
public class ArkivaFrame extends javax.swing.JInternalFrame {

    ArkivaInterface arkivaR = new ArkivaRepository();
    ProfesoriInterface profR = new ProfesoriRepository();
    ArkivaTableModel arkivaTable = new ArkivaTableModel();
    private byte[] array = null;
    private String ext;

    /**
     * Creates new form ArkivaFrame
     */
    public ArkivaFrame() {
        initComponents();
        tabelaLoad();
    }

    public void emptyObject() {
        tabela.clearSelection();
        emritxt.setText("");
        filetxt.setText("");
        array = null;
    }

    private void tabelaLoad() {
        List<Arkiva> lista = arkivaR.findAll();
        arkivaTable.add(lista);
        tabela.setModel(arkivaTable);
        arkivaTable.fireTableDataChanged();
        tabelaSelectedIndexChange();

    }

    private void tabelaSelectedIndexChange() {
        final ListSelectionModel rowSM = tabela.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent Ise) {
                if (Ise.getValueIsAdjusting()) {
                    return;
                }
                ListSelectionModel rowSM = (ListSelectionModel) Ise.getSource();
                int selectedIndex = rowSM.getAnchorSelectionIndex();
                if (selectedIndex > -1) {
                    Arkiva a = arkivaTable.getArkiva(selectedIndex);
                    filetxt.setText("");
                    emritxt.setText(a.getEmriFajllit());
                    array = a.getFajlli();
                    ext = a.getMbrapaShtesa();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        Ngarkobtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        Shkarkobtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        filetxt = new javax.swing.JTextField();
        Zgjedhbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        emritxt = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Arkiva");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabela);

        Ngarkobtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Ngarkobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/upload.png"))); // NOI18N
        Ngarkobtn.setText("Ngarko File-in");
        Ngarkobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NgarkobtnActionPerformed(evt);
            }
        });

        deletebtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deletebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/delete.png"))); // NOI18N
        deletebtn.setText("Fshije File-in");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        Shkarkobtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Shkarkobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/shkarko.png"))); // NOI18N
        Shkarkobtn.setText("Shkarko File-in");
        Shkarkobtn.setPreferredSize(new java.awt.Dimension(150, 33));
        Shkarkobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShkarkobtnActionPerformed(evt);
            }
        });

        cancelbtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cancelbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/cancel.png"))); // NOI18N
        cancelbtn.setText("Anulo");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(filetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 231, 30));

        Zgjedhbtn.setText("Zgjedh File-in");
        Zgjedhbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZgjedhbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Zgjedhbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 120, 30));

        jLabel1.setText("Emri fajllit : ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 70, 30));

        emritxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emritxtKeyTyped(evt);
            }
        });
        jPanel1.add(emritxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 185, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ngarkobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Shkarkobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ngarkobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Shkarkobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ZgjedhbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZgjedhbtnActionPerformed
        JFileChooser fch = new JFileChooser();
        fch.setPreferredSize(new Dimension(700, 500));
        fch.setDialogTitle("Ngarko File-in");
        int returnVal = fch.showSaveDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                array = Files.readAllBytes(new File(fch.getSelectedFile().getAbsolutePath()).toPath());
            } catch (IOException ex) {
                Logger.getLogger(ArkivaFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            filetxt.setText(fch.getSelectedFile().getAbsolutePath());
            ext = FilenameUtils.getExtension(fch.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_ZgjedhbtnActionPerformed

    private void NgarkobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NgarkobtnActionPerformed
        if (emritxt.getText().equals("") || filetxt.getText().equals("") || (ext.equals("") || ext == null)) {
            JOptionPane.showMessageDialog(this, "Ju lutem plotesoni çdo fushë !!!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            Arkiva a = new Arkiva();
            a.setFajlli(array);
            a.setEmriFajllit(emritxt.getText());
            Date d = new Date();
            a.setDataPublikimit(d);
            a.setMbrapaShtesa("." + ext);
            try {
                arkivaR.create(a);
            } catch (ArkivaException ex) {
                Logger.getLogger(ArkivaFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            emptyObject();
            tabelaLoad();
            JOptionPane.showMessageDialog(this, "File u ngarkua me sukses", "Sukses", 1);
        }
    }//GEN-LAST:event_NgarkobtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        try {
            int row = tabela.getSelectedRow();
            if (row > -1) {
                Object[] ob = {"Po", "Jo"};
                int i = javax.swing.JOptionPane.showOptionDialog(this, "A dëshironi ta fshini ?", "Fshirja", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);
                if (i == 0) {
                    Arkiva a = this.arkivaTable.getArkiva(row);
                    arkivaR.remove(a);
                    tabelaLoad();
                    emptyObject();
                    JOptionPane.showMessageDialog(this, "E dhëna është fshir me sukses !");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Nuk keni selektuar asgjë për të fshir !");
            }
        } catch (ArkivaException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void ShkarkobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShkarkobtnActionPerformed
        JFileChooser fch = new JFileChooser();
        fch.setPreferredSize(new Dimension(700, 500));
        fch.setDialogTitle("Shkarko File-in");
        fch.setSelectedFile(new File(emritxt.getText()));
        int returnVal = fch.showSaveDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                FileOutputStream fs = new FileOutputStream(fch.getSelectedFile().getAbsolutePath() + ext);
                fs.write(array);
                fs.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(ArkivaFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(ArkivaFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(this, "E dhëna është shkarkuar me sukses !");
            Object[] ob = {"Po", "Jo"};
            int i = javax.swing.JOptionPane.showOptionDialog(this, "A dëshironi ta hapni fajllin e shkarkuar ?", "Hapja", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);
            if (i == 0) {
                Desktop desktop = Desktop.getDesktop();
                File file = new File(fch.getSelectedFile().getAbsolutePath() + ext);
                try {
                    desktop.open(file);
                } catch (IOException ex) {
                    Logger.getLogger(ArkivaFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }

    }//GEN-LAST:event_ShkarkobtnActionPerformed

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        tabela.clearSelection();
        emptyObject();

    }//GEN-LAST:event_cancelbtnActionPerformed

    private void emritxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emritxtKeyTyped
        char c = evt.getKeyChar();
        String number =  emritxt.getText();
        if(number.length()>49 ){
            JOptionPane.showMessageDialog(this, "Keni tejakaluar numrin e lejuar te shkronjave(50)", "Gabim" , 0);
            evt.consume();
        }
    }//GEN-LAST:event_emritxtKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton Ngarkobtn;
    private javax.swing.JButton Shkarkobtn;
    protected javax.swing.JButton Zgjedhbtn;
    private javax.swing.JButton cancelbtn;
    protected javax.swing.JButton deletebtn;
    protected javax.swing.JTextField emritxt;
    protected javax.swing.JTextField filetxt;
    protected javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
