/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.Fatura;
import BL.FaturaDetaje;
import BL.Lenda;
import DAL.FaturaDetajeException;
import DAL.FaturaDetajeInterface;
import DAL.FaturaDetajeRepository;
import DAL.FaturaException;
import DAL.FaturaInterface;
import DAL.FaturaRepository;
import DAL.LendaInterface;
import DAL.LendaRepository;
import Model.FaturaDetajeTableModel;
import Model.KomboBox.LendaComboBoxModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.sun.glass.events.KeyEvent;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.io.FileOutputStream;
import static java.lang.Character.isDigit;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Fatlum
 */
public class FaturaDetajeFrame extends javax.swing.JInternalFrame {

    FaturaDetajeInterface faturaR = new FaturaDetajeRepository();
    FaturaDetajeTableModel faturaTable = new FaturaDetajeTableModel();
    FaturaInterface faturaRepository = new FaturaRepository();
    List<FaturaDetaje> lista;
    List<FaturaDetaje> list = new ArrayList<FaturaDetaje>();
    LendaInterface lendaR = new LendaRepository();
    LendaComboBoxModel lendamodelcombo;
    String nrFatures = null;

    /**
     * Creates new form FaturaDetajeFrame
     */
    public FaturaDetajeFrame() {
        initComponents();
        tabelaLoad();
        populateChooserLenda();
    }

    public void populateChooserLenda() {
        List<Lenda> LendaID = lendaR.findAll();
        lendamodelcombo = new LendaComboBoxModel(LendaID);
        LendaChooser.setModel(lendamodelcombo);
    }

    public void emptyObject() {
        tabela.clearSelection();
        LendaChooser.setSelectedIndex(-1);
        LendaChooser.repaint();
        shumatxt.setText("");
        sasiatxt.setText("");
        list = null;
    }

    private void tabelaLoad() {
        List nullList = new ArrayList();
        faturaTable.add(nullList);
        tabela.setModel(faturaTable);
        faturaTable.fireTableDataChanged();
    }

    private void tabelaLoadFaturat(List<FaturaDetaje> f) {
        faturaTable.add(f);
        tabela.setModel(faturaTable);
        faturaTable.fireTableDataChanged();
    }

    private double njehsoTotalin() {
        double Totali = 0;
        for (int i = 0; i < tabela.getRowCount(); i++) {
            Totali += (double) tabela.getValueAt(i, 1) * (int) tabela.getValueAt(i, 2);
        }
        return Totali;
    }

    private String gjeneroNrFatures() {
        List<Fatura> listFatura = faturaRepository.findAll();
        String n = "EC" + (1000000 + listFatura.size() + 1);
        nrFatures = n;
        return n;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        shumatxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sasiatxt = new javax.swing.JTextField();
        LendaChooser = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        savebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        printobtn = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Fatura");

        jLabel3.setText("Shuma: ");

        shumatxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                shumatxtKeyTyped(evt);
            }
        });

        jLabel4.setText("Sasia:    ");

        sasiatxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sasiatxtKeyTyped(evt);
            }
        });

        LendaChooser.setPreferredSize(new java.awt.Dimension(150, 30));

        jLabel1.setText("Lenda:  ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LendaChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shumatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sasiatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LendaChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(sasiatxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shumatxt, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        savebtn.setText("Ruaj");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        deletebtn.setText("Fshij");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        cancelbtn.setText("Anulo");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabela);

        printobtn.setText("Printo Faturen");
        printobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printobtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(printobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(savebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(printobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        if (LendaChooser.getSelectedIndex() == -1 || shumatxt.getText().equals("") || sasiatxt.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ju lutem plotesoni çdo fushë !!!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            FaturaDetaje f = new FaturaDetaje();
            Lenda l = (Lenda) LendaChooser.getSelectedItem();
            f.setLendaID(l);
            f.setSasia(Integer.parseInt(sasiatxt.getText()));
            f.setShuma(Double.parseDouble(shumatxt.getText()));
            list.add(f);
            tableLoad1(list);
        }
    }//GEN-LAST:event_savebtnActionPerformed

    private void ruaj() {
        try {
            int row = tabela.getSelectedRow();
                if (row == -1) {
                    Fatura f = new Fatura();
                    f.setNumriFatures(gjeneroNrFatures());
                    f.setTotali(njehsoTotalin());
                    faturaRepository.create(f);
                    for (int i = 0; i < list.size(); i++) {
                        list.get(i).setFaturaID(f);
                        faturaR.create(list.get(i));
                    }

                } else {
                    FaturaDetaje fatura = this.faturaTable.getFaturaDetaje(row);
                    fatura.setLendaID((Lenda) LendaChooser.getSelectedItem());
                    fatura.setShuma(Double.parseDouble(shumatxt.getText()));
                    fatura.setSasia(Integer.parseInt(sasiatxt.getText()));
                    faturaR.edit(fatura);
                    JOptionPane.showMessageDialog(this, "E dhëna u editua me sukses !");
                }
                tabelaLoadFaturat(list);
                emptyObject();

        } catch (HeadlessException | NumberFormatException ex) {
            Logger.getLogger(AdministrataFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FaturaException | FaturaDetajeException ex) {
            Logger.getLogger(FaturaDetajeFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        try {
            int row = tabela.getSelectedRow();
            if (row > -1) {
                Object[] ob = {"Po", "Jo"};
                int i = javax.swing.JOptionPane.showOptionDialog(this, "A dëshironi ta fshini ?", "Fshirja", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);
                if (i == 0) {
                    FaturaDetaje fatura = this.faturaTable.getFaturaDetaje(row);
                    faturaR.remove(fatura);
                    emptyObject();
                    JOptionPane.showMessageDialog(this, "E dhëna është fshir me sukses !");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Nuk keni selektuar asgjë për të fshir !");
            }
        } catch (FaturaDetajeException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        tabela.clearSelection();
        tabelaLoad();
        emptyObject();
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void printobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printobtnActionPerformed
        try {
            if (LendaChooser.getSelectedIndex() == -1 || shumatxt.getText().equals("") || sasiatxt.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Ju lutem plotesoni çdo fushë !!!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                ruaj();
                JFileChooser fch = new JFileChooser();
                fch.setFileSelectionMode(JFileChooser.FILES_ONLY);
                fch.setPreferredSize(new Dimension(700, 500));
                fch.setDialogTitle("Ruaj raportin");
                int returnVal = fch.showSaveDialog(null);
                if (returnVal == JFileChooser.APPROVE_OPTION) {
                    Document doc = new Document(PageSize.A4.rotate());
                    FileOutputStream outtPutFile = new FileOutputStream(fch.getSelectedFile().getAbsolutePath() + " Fatura.pdf");
                    PdfWriter.getInstance(doc, outtPutFile);
                    doc.open();
                    doc.add(new Paragraph("Numri Fatures: " + nrFatures));
                    doc.add(new Paragraph(""));
                    doc.add(new Paragraph(""));
                    PdfPTable pdfTable = new PdfPTable(tabela.getColumnCount());

                    for (int i = 0; i < tabela.getColumnCount(); i++) {
                        pdfTable.addCell(tabela.getColumnName(i));
                    }

                    for (int rows = 0; rows < tabela.getRowCount(); rows++) {
                        for (int cols = 0; cols < tabela.getColumnCount(); cols++) {
                            pdfTable.addCell(tabela.getModel().getValueAt(rows, cols).toString());

                        }
                    }
                    doc.add(new Paragraph("\n"));
                    doc.add(pdfTable);
                    doc.add(new Paragraph("Total : " + njehsoTotalin()));
                    doc.close();

                    JOptionPane.showMessageDialog(this, "Fatura u ruajt me sukses");
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ndodhi nje gabim gjat ruajtes \nRaporti nuk u ruajt", "Gabim", 0);
            Logger.getLogger(FaturaDetajeFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_printobtnActionPerformed

    
    private void shumatxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_shumatxtKeyTyped
        char [] t = shumatxt.getText().toCharArray();
        String palidhje = shumatxt.getText();
        char c = evt.getKeyChar();
        if ((!(isDigit(c)) || c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_SHIFT )&&(c == KeyEvent.VK_PERIOD && palidhje.contains("."))) {
            evt.consume();
        }
        
        String number =  shumatxt.getText();
        if(number.length()>5 ){
            JOptionPane.showMessageDialog(this, "Keni tejakaluar numrin e lejuar (3-shifror)", "Gabim" , 0);
            evt.consume();
        }
    }//GEN-LAST:event_shumatxtKeyTyped

    private void sasiatxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sasiatxtKeyTyped
        char c = evt.getKeyChar();
        if (!((isDigit(c)) || c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_SHIFT)) {
            evt.consume();
        }
         String number =  sasiatxt.getText();
        if(number.length()>2 ){
            JOptionPane.showMessageDialog(this, "Keni tejakaluar numrin e lejuar (3-shifror)", "Gabim" , 0);
            evt.consume();
        }
    }//GEN-LAST:event_sasiatxtKeyTyped
    private void tableLoad1(List<FaturaDetaje> list) {
        faturaTable.add(list);
        tabela.setModel(faturaTable);
        faturaTable.fireTableDataChanged();
//        tabelaSelectedIndexChange();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Lenda> LendaChooser;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printobtn;
    private javax.swing.JTextField sasiatxt;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField shumatxt;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
