/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.Grupi;
import BL.Orari;
import DAL.GrupiException;
import DAL.GrupiInterface;
import DAL.GrupiRepository;
import DAL.OrariInterface;
import DAL.OrariRepository;
import Model.GrupiTableModel;
import com.sun.glass.events.KeyEvent;
import static java.lang.Character.isDigit;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Arbër Suka
 */
public class GrupiForm extends javax.swing.JInternalFrame {

    GrupiInterface grupiR = new GrupiRepository();
    OrariInterface orariR = new OrariRepository();
    GrupiTableModel grupiTable = new GrupiTableModel();
    private List<Orari> orariList;

    /**
     * Creates new form GrupiForm
     */
    public GrupiForm() {
        initComponents();
        tabelaLoad();
    }

    

    public void emptyObject() {
        tabela.clearSelection();
        emritxt.setText("");
        kapacitetitxt.setText("");
    }
    private void tabelaLoad() {
        List<Grupi> lista = grupiR.findAll();
        grupiTable.add(lista);
        tabela.setModel(grupiTable);
        grupiTable.fireTableDataChanged();
        tabelaSelectedIndexChange();
    }
    private void tabelaSelectedIndexChange() {
           final ListSelectionModel rowSM = tabela.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent Ise) {
                if (Ise.getValueIsAdjusting()) {
                    return;
                }
                ListSelectionModel rowSM = (ListSelectionModel) Ise.getSource();
                int selectedIndex = rowSM.getAnchorSelectionIndex();
                if (selectedIndex > -1) {
                    Grupi grupi = grupiTable.getGrupi(selectedIndex);
                    grupi.setEmriGrupit(grupi.getEmriGrupit());
                    grupi.setNrStudenteveGrup(grupi.getNrStudenteveGrup());

                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        ruajbtn = new javax.swing.JButton();
        fshijebtn = new javax.swing.JButton();
        anulobtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        emritxt = new javax.swing.JTextField();
        kapacitetitxt = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Grupi");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        ruajbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ruajbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/save.png"))); // NOI18N
        ruajbtn.setText("Ruaj");
        ruajbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruajbtnActionPerformed(evt);
            }
        });

        fshijebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fshijebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/delete.png"))); // NOI18N
        fshijebtn.setText("Fshije");
        fshijebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fshijebtnActionPerformed(evt);
            }
        });

        anulobtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        anulobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/cancel.png"))); // NOI18N
        anulobtn.setText("Aunlo");
        anulobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anulobtnActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Kapaciteti");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 150, 26));

        jLabel1.setText("Emri grupit");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 150, 26));

        emritxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emritxtKeyTyped(evt);
            }
        });
        jPanel1.add(emritxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 150, 30));

        kapacitetitxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kapacitetitxtKeyTyped(evt);
            }
        });
        jPanel1.add(kapacitetitxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 150, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ruajbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fshijebtn)
                        .addGap(22, 22, 22)
                        .addComponent(anulobtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ruajbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fshijebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anulobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ruajbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruajbtnActionPerformed
        try {

            int row = tabela.getSelectedRow();
            if (emritxt.getText().equals("") || kapacitetitxt.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Ju lutem plotesoni çdo fushë !!!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                if (row == -1) {
                    Grupi grup = new Grupi();
                    grup.setEmriGrupit(emritxt.getText());
                    grup.setNrStudenteveGrup(Integer.parseInt(kapacitetitxt.getText()));
                    grupiR.create(grup);
                    JOptionPane.showMessageDialog(this, "E dhëna u ruajt me sukses !");
                } else {
                    Grupi grup = new Grupi();
                    grup.setEmriGrupit(emritxt.getText());
                    grup.setNrStudenteveGrup(Integer.parseInt(kapacitetitxt.getText()));
                    grupiR.create(grup);
                    JOptionPane.showMessageDialog(this, "E dhëna u editua me sukses !");
                }
                emptyObject();
                tabelaLoad();
            }

        } catch (GrupiException pe) {
            JOptionPane.showMessageDialog(this, pe.getMessage());
        } catch (Exception ex) {
            Logger.getLogger(AdministrataFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ruajbtnActionPerformed

    private void fshijebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fshijebtnActionPerformed
         try {
            int row = tabela.getSelectedRow();
            if (row > -1) {
                Object[] ob = {"Po", "Jo"};
                int i = javax.swing.JOptionPane.showOptionDialog(this, "A dëshironi ta fshini ?", "Fshirja", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);
                if (i == 0) {
                    Grupi g = this.grupiTable.getGrupi(row);
                    grupiR.remove(g);
                    tabelaLoad();
                    emptyObject();
                    JOptionPane.showMessageDialog(this, "E dhëna është fshir me sukses !");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Nuk keni selektuar asgjë për të fshir !");
            }
        } catch (GrupiException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_fshijebtnActionPerformed

    private void anulobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anulobtnActionPerformed
        tabela.clearSelection();
        emptyObject();
    }//GEN-LAST:event_anulobtnActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        int row = tabela.getSelectedRow();
        if (row > -1) {
            Grupi grup = grupiTable.getGrupi(row);
            emritxt.setText(grup.getEmriGrupit());
            kapacitetitxt.setText(""+ grup.getNrStudenteveGrup());

        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void kapacitetitxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kapacitetitxtKeyTyped
        char c = evt.getKeyChar();
        if (!((isDigit(c)) || c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_SHIFT)) {
            evt.consume();
        }
        String number =  kapacitetitxt.getText();
        //vec nese eshte number dhe eshte 3 shifror e qet kete jOptionPane
        if(number.length()>2 && isDigit(c)){
            JOptionPane.showMessageDialog(this, "Keni tejakaluar numrin e lejuar te numrave(3)", "Gabim" , 0);
            evt.consume();
        }
    }//GEN-LAST:event_kapacitetitxtKeyTyped

    private void emritxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emritxtKeyTyped
        char c = evt.getKeyChar();
        if (!((isDigit(c)) || c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_SHIFT)) {
            evt.consume();
        }
        String number =  emritxt.getText();
        //vec nese eshte number dhe eshte 3 shifror e qet kete jOptionPane
        if(number.length()>29 && isDigit(c)){
            JOptionPane.showMessageDialog(this, "Keni tejakaluar numrin e lejuar te Shkronjave(30)", "Gabim" , 0);
            evt.consume();
        }
    }//GEN-LAST:event_emritxtKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anulobtn;
    private javax.swing.JTextField emritxt;
    private javax.swing.JButton fshijebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kapacitetitxt;
    private javax.swing.JButton ruajbtn;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
