/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.Perdoruesi;
import BL.Profesori;
import BL.Studenti;
import DAL.PerdoruesiInterface;
import DAL.PerdoruesiRepository;
import DAL.ProfesoriInterface;
import DAL.ProfesoriRepository;
import DAL.StudentiInterface;
import DAL.StudentiRepository;
import static GUI.MainFrame.studenti;
import Regex.EmailValidator;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Arbër Suka
 */
public class LoginFrame extends javax.swing.JFrame {

    StudentiInterface studentR = new StudentiRepository();
    ProfesoriInterface profR = new ProfesoriRepository();
    PerdoruesiInterface userRepository = new PerdoruesiRepository();
    private Perdoruesi u;

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        gabimlbl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        perdoruesitxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Passwordtxt = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        kyqubtn = new javax.swing.JButton();
        gabimlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        perdoruesitxt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        perdoruesitxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perdoruesitxtActionPerformed(evt);
            }
        });
        perdoruesitxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                perdoruesitxtKeyTyped(evt);
            }
        });
        jPanel1.add(perdoruesitxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 267, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Përdoruesi");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 160, 60));

        Passwordtxt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Passwordtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordtxtFocusLost(evt);
            }
        });
        Passwordtxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordtxtMouseClicked(evt);
            }
        });
        Passwordtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PasswordtxtKeyTyped(evt);
            }
        });
        jPanel1.add(Passwordtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 267, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Fjalekalimi");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 160, 60));

        kyqubtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/admin.png"))); // NOI18N
        kyqubtn.setText("Kyquni");
        kyqubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kyqubtnActionPerformed(evt);
            }
        });
        jPanel1.add(kyqubtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 210, 60));

        gabimlbl.setForeground(new java.awt.Color(255, 0, 0));
        gabimlbl.setText("Email adresa nuk është valide");
        jPanel1.add(gabimlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 260, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(768, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void perdoruesitxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perdoruesitxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perdoruesitxtActionPerformed

    private void kyqubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kyqubtnActionPerformed
        String password = new String(Passwordtxt.getPassword());
        try {
            u = userRepository.findByUsername(perdoruesitxt.getText(), password);
            if (u != null) {
                MainFrame am = new MainFrame();
                am.setPerdoruesi(u);
                if (password.equals(u.getPasswordiPerdoruesit())) {

                    if (u.getRoli().equalsIgnoreCase("Administrat")) {
                        am.setVisible(true);
                        dispose();
                    } else if (u.getRoli().equalsIgnoreCase("Student")) {
                        StudentiProfilFrame s = new StudentiProfilFrame();
                        Studenti stud = findStudenti();
                        s.shtoTeDhenat(stud);
                        s.setStudenti(stud);
                        s.setVisible(true);
                        dispose();

                    } else {
                        ProfesoriProfilFrame p = new ProfesoriProfilFrame();
                        Profesori prof = findProfesori();
                        p.shtoTeDhenat(prof);
                        p.setProofesori(prof);
                        p.setVisible(true);
                        dispose();
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_kyqubtnActionPerformed

    private Studenti findStudenti(){
        Studenti s = new Studenti();
        List<Studenti> studentList = studentR.findAll();
            for (int i = 0; i < studentList.size(); i++) {
                if (studentList.get(i).getEmail().equals(u.getEmriPerdoruesit())) {
                    s = studentList.get(i);
                }
            }
        return s;
    }
    
    private Profesori findProfesori(){
        Profesori p = new Profesori();
        List<Profesori> profesoriList = profR.findAll();
            for (int i = 0; i < profesoriList.size(); i++) {
                if (profesoriList.get(i).getEmail().equals(u.getEmriPerdoruesit())) {
                    p = profesoriList.get(i);
                }
            }
        return p;
    }
    
    private void PasswordtxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordtxtMouseClicked

    }//GEN-LAST:event_PasswordtxtMouseClicked

    private void PasswordtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordtxtKeyTyped
        char enter = evt.getKeyChar();
        if (enter == KeyEvent.VK_ENTER) {
            String password = new String(Passwordtxt.getPassword());
            try {
                u = userRepository.findByUsername(perdoruesitxt.getText(), password);
                if (u != null) {
                    MainFrame am = new MainFrame();
                am.setPerdoruesi(u);
                if (password.equals(u.getPasswordiPerdoruesit())) {

                    if (u.getRoli().equalsIgnoreCase("Administrat")) {
                        am.setVisible(true);
                        dispose();
                    } else if (u.getRoli().equalsIgnoreCase("Student")) {
                        StudentiProfilFrame s = new StudentiProfilFrame();
                        Studenti stud = findStudenti();
                        s.shtoTeDhenat(stud);
                        s.setStudenti(stud);
                        s.setVisible(true);
                        dispose();

                    } else {
                        ProfesoriProfilFrame p = new ProfesoriProfilFrame();
                        Profesori prof = findProfesori();
                        p.shtoTeDhenat(prof);
                        p.setProofesori(prof);
                        p.setVisible(true);
                        dispose();
                    }
                }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_PasswordtxtKeyTyped

    private void perdoruesitxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_perdoruesitxtKeyTyped

    }//GEN-LAST:event_perdoruesitxtKeyTyped

    private void PasswordtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordtxtFocusGained
        EmailValidator emailValidator = new EmailValidator();
        if (!emailValidator.validate(perdoruesitxt.getText().trim())) {
            gabimlbl.setVisible(true);
        }
    }//GEN-LAST:event_PasswordtxtFocusGained

    private void PasswordtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordtxtFocusLost
        gabimlbl.setVisible(false);
    }//GEN-LAST:event_PasswordtxtFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Passwordtxt;
    private javax.swing.JLabel gabimlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kyqubtn;
    private javax.swing.JTextField perdoruesitxt;
    // End of variables declaration//GEN-END:variables
}
