/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.Adminstrata;
import BL.Pagesa;
import BL.Perdoruesi;
import BL.Profesori;
import BL.Studenti;
import DAL.AdministrataRepository;
import DAL.AdminstrataInterface;
import DAL.PerdoruesiInterface;
import DAL.PerdoruesiRepository;
import DAL.ProfesoriInterface;
import DAL.ProfesoriRepository;
import DAL.StudentiInterface;
import DAL.StudentiRepository;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Arbër Suka
 */
public class MainFrame extends javax.swing.JFrame {

    PerdoruesiInterface perdoruesiR = new PerdoruesiRepository();
    ProfesoriInterface profR = new ProfesoriRepository();
    StudentiInterface studentR = new StudentiRepository();
    AdminstrataInterface adminR = new AdministrataRepository();

    private Adminstrata admin;
    public static Studenti studenti;
    private Profesori prof;
    private Perdoruesi perdoruesi;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public void setPerdoruesi(Perdoruesi p) {
        perdoruesi = p;
    }

    public Perdoruesi getPerdoruesi() {
        return perdoruesi;
    }

    private void findPerdoruesi() {
        if (perdoruesi.getRoli().equalsIgnoreCase("Administrat")) {
            List<Adminstrata> adminList = adminR.findAll();
            for (int i = 0; i < adminList.size(); i++) {
                if (adminList.get(i).getEmail().equalsIgnoreCase(perdoruesi.getEmriPerdoruesit())) {
                    admin = adminList.get(i);
                }
            }
        } else if (perdoruesi.getRoli().equalsIgnoreCase("Profesor")) {
            List<Profesori> profList = profR.findAll();
            for (int i = 0; i < profList.size(); i++) {
                if (profList.get(i).getEmail().equalsIgnoreCase(perdoruesi.getEmriPerdoruesit())) {
                    prof = profList.get(i);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenu16 = new javax.swing.JMenu();
        DesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        AdminMenu = new javax.swing.JMenu();
        addAdminin = new javax.swing.JMenuItem();
        profaMenu = new javax.swing.JMenu();
        addProfen = new javax.swing.JMenuItem();
        studentMenu = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        lendaMenu = new javax.swing.JMenu();
        addLenda = new javax.swing.JMenuItem();
        sallMenu = new javax.swing.JMenu();
        addSallen = new javax.swing.JMenuItem();
        orariMenu = new javax.swing.JMenu();
        addOrarin = new javax.swing.JMenuItem();
        grupiMenu = new javax.swing.JMenu();
        addGrupin = new javax.swing.JMenuItem();
        qytetiMenu = new javax.swing.JMenu();
        addQytetin = new javax.swing.JMenuItem();
        notaMenu = new javax.swing.JMenu();
        addNota = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        faturaDetaje = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        jMenu3.setText("jMenu3");

        jMenu2.setText("jMenu2");

        jMenu4.setText("jMenu4");

        jMenu6.setText("jMenu6");

        jMenu7.setText("jMenu7");

        jMenu8.setText("File");
        jMenuBar2.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar2.add(jMenu9);

        jMenu10.setText("File");
        jMenuBar3.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar3.add(jMenu11);

        jMenu12.setText("jMenu12");

        jMenu13.setText("jMenu13");

        jMenu16.setText("jMenu16");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Frame");
        setMinimumSize(new java.awt.Dimension(1000, 700));

        DesktopPane.setPreferredSize(new java.awt.Dimension(1000, 700));

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        AdminMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/admin.png"))); // NOI18N
        AdminMenu.setText("Administratori ");

        addAdminin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/Actions-list-add-user-icon.png"))); // NOI18N
        addAdminin.setText("Shto Administrator");
        addAdminin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdmininActionPerformed(evt);
            }
        });
        AdminMenu.add(addAdminin);

        jMenuBar1.add(AdminMenu);

        profaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/profesor.png"))); // NOI18N
        profaMenu.setText("Profesori");

        addProfen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/Actions-list-add-user-icon.png"))); // NOI18N
        addProfen.setText("Shto Profesorin");
        addProfen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProfenActionPerformed(evt);
            }
        });
        profaMenu.add(addProfen);

        jMenuBar1.add(profaMenu);

        studentMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/studenti.png"))); // NOI18N
        studentMenu.setText("Studenti");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/Actions-list-add-user-icon.png"))); // NOI18N
        jMenuItem7.setText("Shto Studentin");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        studentMenu.add(jMenuItem7);

        jMenuBar1.add(studentMenu);

        lendaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/lenda.png"))); // NOI18N
        lendaMenu.setText("Lenda");

        addLenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/lenda.png"))); // NOI18N
        addLenda.setText("Shto Lenden");
        addLenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLendaActionPerformed(evt);
            }
        });
        lendaMenu.add(addLenda);

        jMenuBar1.add(lendaMenu);

        sallMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/salla.png"))); // NOI18N
        sallMenu.setText("Salla");

        addSallen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/salla.png"))); // NOI18N
        addSallen.setText("Shto Sallen");
        addSallen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSallenActionPerformed(evt);
            }
        });
        sallMenu.add(addSallen);

        jMenuBar1.add(sallMenu);

        orariMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/orari.png"))); // NOI18N
        orariMenu.setText("Orari");

        addOrarin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/orari.png"))); // NOI18N
        addOrarin.setText("Shto Orar");
        addOrarin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrarinActionPerformed(evt);
            }
        });
        orariMenu.add(addOrarin);

        jMenuBar1.add(orariMenu);

        grupiMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/grupi.png"))); // NOI18N
        grupiMenu.setText("Grupi");

        addGrupin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/grupi.png"))); // NOI18N
        addGrupin.setText("Shto Grupin");
        addGrupin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGrupinActionPerformed(evt);
            }
        });
        grupiMenu.add(addGrupin);

        jMenuBar1.add(grupiMenu);

        qytetiMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/qyteti.png"))); // NOI18N
        qytetiMenu.setText("Qyteti");

        addQytetin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/qyteti.png"))); // NOI18N
        addQytetin.setText("Shto Qytetin");
        addQytetin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addQytetinActionPerformed(evt);
            }
        });
        qytetiMenu.add(addQytetin);

        jMenuBar1.add(qytetiMenu);

        notaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/nota.png"))); // NOI18N
        notaMenu.setText("Nota");

        addNota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/nota.png"))); // NOI18N
        addNota.setText("Vendos noten");
        addNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNotaActionPerformed(evt);
            }
        });
        notaMenu.add(addNota);

        jMenuBar1.add(notaMenu);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/menu.png"))); // NOI18N
        jMenu1.setText("Menu");

        jMenuItem9.setText("Pagesat");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem9);

        faturaDetaje.setText("FaturaDetaje");
        faturaDetaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faturaDetajeActionPerformed(evt);
            }
        });
        jMenu1.add(faturaDetaje);

        jMenuItem8.setText("Informata per ne");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem4.setText("Shkyqu");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1016, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        DesktopPane.removeAll();
        LoginFrame l = new LoginFrame();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void addProfenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProfenActionPerformed
        DesktopPane.removeAll();
        ProfesoriFrame p = new ProfesoriFrame();
        DesktopPane.add(p);
        p.show();
    }//GEN-LAST:event_addProfenActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        DesktopPane.removeAll();
        StudentiFrame s = new StudentiFrame();
        DesktopPane.add(s);
        s.show();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void addSallenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSallenActionPerformed
        DesktopPane.removeAll();
        SallaFrame s = new SallaFrame();
        DesktopPane.add(s);
        s.show();
    }//GEN-LAST:event_addSallenActionPerformed

    private void addAdmininActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdmininActionPerformed
        DesktopPane.removeAll();
        AdministrataFrame a = new AdministrataFrame();
        DesktopPane.add(a);
        a.show();
    }//GEN-LAST:event_addAdmininActionPerformed

    private void addLendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLendaActionPerformed
        DesktopPane.removeAll();
        LendaFrame l = new LendaFrame();
        DesktopPane.add(l);
        l.show();
    }//GEN-LAST:event_addLendaActionPerformed

    private void addOrarinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrarinActionPerformed
        DesktopPane.removeAll();
        OrariFrame o = new OrariFrame();
        DesktopPane.add(o);
        o.show();
    }//GEN-LAST:event_addOrarinActionPerformed

    private void addGrupinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGrupinActionPerformed
        DesktopPane.removeAll();
        GrupiForm g = new GrupiForm();
        DesktopPane.add(g);
        g.show();
    }//GEN-LAST:event_addGrupinActionPerformed

    private void addQytetinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addQytetinActionPerformed
        DesktopPane.removeAll();
        QytetiFrame q = new QytetiFrame();
        DesktopPane.add(q);
        q.show();
    }//GEN-LAST:event_addQytetinActionPerformed

    private void addNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNotaActionPerformed
        DesktopPane.removeAll();
        NotaFrame n = new NotaFrame();
        DesktopPane.add(n);
        n.show();
    }//GEN-LAST:event_addNotaActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        DesktopPane.removeAll();
        AboutFrame a = new AboutFrame();
        DesktopPane.add(a);
        a.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void faturaDetajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faturaDetajeActionPerformed
        DesktopPane.removeAll();
        FaturaDetajeFrame fd = new FaturaDetajeFrame();
        DesktopPane.add(fd);
        fd.show();
    }//GEN-LAST:event_faturaDetajeActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        DesktopPane.removeAll();
        PagesaFrame p = new PagesaFrame();
        DesktopPane.add(p);
        p.show();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu AdminMenu;
    public static javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenuItem addAdminin;
    private javax.swing.JMenuItem addGrupin;
    private javax.swing.JMenuItem addLenda;
    private javax.swing.JMenuItem addNota;
    private javax.swing.JMenuItem addOrarin;
    private javax.swing.JMenuItem addProfen;
    private javax.swing.JMenuItem addQytetin;
    private javax.swing.JMenuItem addSallen;
    private javax.swing.JMenuItem faturaDetaje;
    public javax.swing.JMenu grupiMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    public javax.swing.JMenu lendaMenu;
    public javax.swing.JMenu notaMenu;
    public javax.swing.JMenu orariMenu;
    public javax.swing.JMenu profaMenu;
    public javax.swing.JMenu qytetiMenu;
    public javax.swing.JMenu sallMenu;
    public javax.swing.JMenu studentMenu;
    // End of variables declaration//GEN-END:variables
}
