/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.Fatura;
import BL.Lenda;
import BL.Pagesa;
import BL.Studenti;
import DAL.FaturaException;
import DAL.FaturaInterface;
import DAL.FaturaRepository;
import DAL.LendaInterface;
import DAL.LendaRepository;
import DAL.PagesaException;
import DAL.PagesaInterface;
import DAL.PagesaRepository;
import DAL.StudentiInterface;
import DAL.StudentiRepository;
import Model.KomboBox.LendaComboBoxModel;
import Model.PagesaTableModel;
import Search.TST;
import com.google.common.collect.Lists;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import static java.lang.Character.isDigit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.export.JExcelApiExporter;

/**
 *
 * @author Arbër Suka
 */
public class PagesaFrame extends javax.swing.JInternalFrame {

    PagesaInterface pagesaR = new PagesaRepository();
    private TST<Integer> tstID = new TST<Integer>();
    private TST<Integer> tstE = new TST<Integer>();
    StudentiInterface studentiR = new StudentiRepository();
    PagesaTableModel pagesaTable = new PagesaTableModel();
    LendaInterface lendaR = new LendaRepository();
    Fatura fatura = new Fatura();
    LendaComboBoxModel lendamodelcombo;
    List<Studenti>lista;
    Studenti studentiK=null;
    
    /**
     * Creates new form PagesaFrame
     */
    public PagesaFrame() {
        initComponents();
        putIntoTstID();
        putIntoTstEmri();
        PanelDropList.setVisible(false);
    }
    
    public void emptyObject(){
        searchtxt.setText("");
        shumatxt.setText("");
        tabela.clearSelection();
    }
    
      private void putIntoTstID() {
        lista = studentiR.findAll();
        for (int i = 0; i < lista.size(); i++) {
            if (!((lista.get(i)).toString1().trim()).equals("")) {
                String key = lista.get(i).toString1().toUpperCase();
                tstID.put(key, i);
            }
        }
    }

    private void putIntoTstEmri() {
        lista = studentiR.findAll();
        for (int i = 0; i < lista.size(); i++) {
            if (!((lista.get(i)).toString2().trim()).equals("")) {
                String key = lista.get(i).toString2().toUpperCase();
                tstE.put(key, i);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        panel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        searchtxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        shumatxt = new javax.swing.JTextField();
        PanelDropList = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        droplist = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        nrFaturestxt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        Ruaj = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exelbtn = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pagesa");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabela);

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Studenti: ");
        panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 52, 27));

        searchtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchtxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchtxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchtxtKeyTyped(evt);
            }
        });
        panel.add(searchtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 160, 30));

        jLabel3.setText("Shuma: ");
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 40, 30));

        shumatxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                shumatxtKeyTyped(evt);
            }
        });
        panel.add(shumatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 100, 30));

        droplist.setInheritsPopupMenu(true);
        droplist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                droplistMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(droplist);

        javax.swing.GroupLayout PanelDropListLayout = new javax.swing.GroupLayout(PanelDropList);
        PanelDropList.setLayout(PanelDropListLayout);
        PanelDropListLayout.setHorizontalGroup(
            PanelDropListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDropListLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        PanelDropListLayout.setVerticalGroup(
            PanelDropListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDropListLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        panel.add(PanelDropList, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 170, 140));

        jLabel4.setText("Nr. Fatures");
        panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 30));

        nrFaturestxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nrFaturestxtKeyTyped(evt);
            }
        });
        panel.add(nrFaturestxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 140, 30));

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/cancel.png"))); // NOI18N
        jButton3.setText("Anulo");

        Ruaj.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Ruaj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/save.png"))); // NOI18N
        Ruaj.setText("Ruaj");
        Ruaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RuajActionPerformed(evt);
            }
        });

        jMenu1.setText("Ruaj");

        exelbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/excel.png"))); // NOI18N
        exelbtn.setText("Ruaj ne Exel");
        exelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exelbtnActionPerformed(evt);
            }
        });
        jMenu1.add(exelbtn);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/pdf.png"))); // NOI18N
        jMenuItem2.setText("Ruaj ne PDF");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/hp_printer.png"))); // NOI18N
        jMenuItem3.setText("Printo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1087, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Ruaj)
                        .addGap(31, 31, 31)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ruaj, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exelbtnActionPerformed
         try {
            JFileChooser fch = new JFileChooser();
            fch.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fch.setPreferredSize(new Dimension(700, 500));
            fch.setDialogTitle("Ruaj raportin");
            int returnVal = fch.showSaveDialog(null);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=EducationCenter;user=sa;password=Avdisuka12");
                String report="C:\\Users\\Arbër Suka\\Desktop\\Projekti LabCourse\\EducationCenter\\PagesaRaport.jrxml";
                JasperReport jr = JasperCompileManager.compileReport(report);
                JasperPrint jp = JasperFillManager.fillReport(jr, null, con);
                JExcelApiExporter exporter = new JExcelApiExporter();
                exporter.setParameter(JRExporterParameter.JASPER_PRINT, jp);
                exporter.setParameter(JRExporterParameter.OUTPUT_FILE_NAME, fch.getSelectedFile().getAbsolutePath() + ".xls");
                exporter.exportReport();
                JOptionPane.showMessageDialog(this, "Raporti u ruajt ne Excel");
            }
        } catch (ClassNotFoundException | SQLException | JRException e) {

            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_exelbtnActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        MessageFormat header = new MessageFormat("Tabela Pagesa");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");

        try{
            tabela.print(JTable.PrintMode.NORMAL, header, footer);

        }
        catch(java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n",e.getMessage());
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try{
           JFileChooser fch = new JFileChooser();
           fch.setFileSelectionMode(JFileChooser.FILES_ONLY);
           fch.setPreferredSize(new Dimension(700, 500));    
           fch.setDialogTitle("Ruaj raportin");
           int returnVal = fch.showSaveDialog(null);
           if (returnVal == JFileChooser.APPROVE_OPTION) {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=EducationCenter;user=sa;password=Avdisuka12");
                String report="C:\\Users\\Arbër Suka\\Desktop\\Projekti LabCourse\\EducationCenter\\PagesaRaport.jrxml";
                JasperReport jr=JasperCompileManager.compileReport(report);
                JasperPrint jp=JasperFillManager.fillReport(jr, null,con);
                JasperExportManager.exportReportToPdfFile(jp,fch.getSelectedFile().getAbsolutePath()+".pdf");
 		JOptionPane.showMessageDialog(this, "Raporti u ruajt ne PDF");
           }
        }catch(ClassNotFoundException | SQLException | JRException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void searchtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtxtKeyReleased
        char c = evt.getKeyChar();
        String t = searchtxt.getText().toUpperCase();
        if (!(c == KeyEvent.VK_CAPS_LOCK || c == KeyEvent.VK_SHIFT )) {
            if(!(t.equals("")||t==null)){
                if(isDigit(t.charAt(0))){
                    Iterable<String> it = tstID.keysWithPrefix(t);
                    List<String> itlist = Lists.newArrayList(it.iterator());
                    String[] st = new String[itlist.size()];
                    
                    for (int i = 0; i < itlist.size(); i++) {
                        st[i] = itlist.get(i);
                    }
                    
                    if(!(st.length==0)){
                        droplist.setListData(st);
                        PanelDropList.setVisible(true);
                        PanelDropList.setFocusable(true);
                        droplist.setFocusable(true);
                    }
                    else
                    PanelDropList.setVisible(false);
                }
                else{
                    Iterable<String> it = tstE.keysWithPrefix(t);
                    List<String> itlist = Lists.newArrayList(it.iterator());
                    String[] st = new String[itlist.size()];
                    
                    for (int i = 0; i < itlist.size(); i++) {
                        st[i] = itlist.get(i);
                    }
                    
                    if(!(st.length==0)){
                        droplist.setListData(st);
                        PanelDropList.setVisible(true);
                          PanelDropList.setFocusable(true);
                        droplist.setFocusable(true);
                    }
                    
                    else
                    PanelDropList.setVisible(false);
                }
            }
            else
            PanelDropList.setVisible(false);
        }
    }//GEN-LAST:event_searchtxtKeyReleased

    private void searchtxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtxtKeyTyped

    }//GEN-LAST:event_searchtxtKeyTyped

    private void droplistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_droplistMouseClicked
        String s = droplist.getSelectedValue();
        Studenti studenti = null;
        if(isDigit(s.charAt(0))){
            for(int i = 0 ; i < lista.size() ; i++){
                if(lista.get(i).toString1().equalsIgnoreCase(s))
                studenti = lista.get(i);
            }
        }
        else{
            for(int i = 0 ; i < lista.size() ; i++){
                if(lista.get(i).toString2().equalsIgnoreCase(s))
                studenti = lista.get(i);
            }
        }
        searchtxt.setText(studenti.getEmri()+" "+studenti.getMbiemri());
        try {
            tabelaLoadPagesat(studenti);
        } catch (PagesaException ex) {
            Logger.getLogger(NotaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        studentiK = studenti;
        PanelDropList.setVisible(false);
    }//GEN-LAST:event_droplistMouseClicked

    private void RuajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RuajActionPerformed
        try {
            int row = tabela.getSelectedRow();
            if (searchtxt.getText().equals("") ||  shumatxt.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Ju lutem plotesoni çdo fushë !!!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                if (row == -1) {
                    
                    
                    Pagesa p = new Pagesa();
                    
                    p.setShumaEPaguar(Double.parseDouble(shumatxt.getText()));
                    p.setStudentiID(studentiK);
                    p.setFaturaID(fatura);

                    pagesaR.create(p);
                    JOptionPane.showMessageDialog(this, "E dhëna u ruajt me sukses");

                }
//                else {
//                    
//                    Lenda l = (Lenda) LendaChooser.getSelectedItem();
//                    int niveli = (int) NiveliChooser.getSelectedItem();

//                    Pagesa p = this.pagesaTable.getNota(row);
//                    p.setLendaID(l);
//                    p.setShumaEPaguar(Double.parseDouble(shumatxt.getText()));
//                    p.setStudentiID(studentiK);

//                    pagesaR.edit(p);
//                    JOptionPane.showMessageDialog(this, "E dhëna u editua me sukses");
//                }
                emptyObject();
                tabelaLoadPagesat(studentiK);
            }

        } catch (PagesaException pe) {
            JOptionPane.showMessageDialog(this, pe.getMessage());
        }
    }//GEN-LAST:event_RuajActionPerformed

    private void nrFaturestxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nrFaturestxtKeyTyped
        char c = evt.getKeyChar();
        if(c == KeyEvent.VK_ENTER){
            FaturaInterface faturaR = new FaturaRepository();
            String t = nrFaturestxt.getText();
            
            try {
                fatura = faturaR.findByNumriFatures(t);
            } catch (FaturaException ex) {
                
                JOptionPane.showMessageDialog(this, "Fatura nuk Ekziston ! ", "Gabim", 0);
                Logger.getLogger(PagesaFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            shumatxt.setText(""+fatura.getTotali());
        }
    }//GEN-LAST:event_nrFaturestxtKeyTyped

    private void searchtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtxtKeyPressed
       droplist.setFocusable(true);
    }//GEN-LAST:event_searchtxtKeyPressed

    int countPoints = 0;
    private void shumatxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_shumatxtKeyTyped
        char [] t = shumatxt.getText().toCharArray();
        String palidhje = shumatxt.getText();
        char c = evt.getKeyChar();
        if ((!((isDigit(c)) || c == com.sun.glass.events.KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_SHIFT )
                && (c == KeyEvent.VK_PERIOD && palidhje.contains(".")))) {
            evt.consume();
        }
        
        String number =  shumatxt.getText();
        if(number.length()>5 && isDigit(c)){
            JOptionPane.showMessageDialog(this, "Keni tejakaluar numrin e lejuar (5-shifror)", "Gabim" , 0);
            evt.consume();
        }
    }//GEN-LAST:event_shumatxtKeyTyped

    public void tabelaLoadPagesat(Studenti s) throws PagesaException {
        List<Pagesa> pagesa = pagesaR.findByStudentiID(s.getStudentiID());
        pagesaTable.add(pagesa);
        tabela.setModel(pagesaTable);
        pagesaTable.fireTableDataChanged();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDropList;
    private javax.swing.JButton Ruaj;
    private javax.swing.JList<String> droplist;
    private javax.swing.JMenuItem exelbtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField nrFaturestxt;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JTextField shumatxt;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
