/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.Qyteti;
import DAL.QytetiException;
import DAL.QytetiInterface;
import DAL.QytetiRepository;
import Model.QytetiTableModel;
import com.sun.glass.events.KeyEvent;
import static java.lang.Character.isAlphabetic;
import static java.lang.Character.isDigit;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Fatlum
 */
public class QytetiFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form QytetiFrame
     */
    QytetiInterface qytetiR = new QytetiRepository();
    QytetiTableModel qytetiTable = new QytetiTableModel();
    List<Qyteti> lista;
    public QytetiFrame() {
        initComponents();
        tabelaLoad();
    }

    public void emptyObject() {
        tabela.clearSelection();
        emriQytetittxt.setText("");
        zipkoditxt.setText("");
    }

    private void tabelaLoad() {
        lista = qytetiR.findAll();
        qytetiTable.add(lista);
        tabela.setModel(qytetiTable);
        qytetiTable.fireTableDataChanged();
        tabelaSelectedIndexChange();
    }

    private void tabelaSelectedIndexChange() {
        final ListSelectionModel rowSM = tabela.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent Ise) {
                if (Ise.getValueIsAdjusting()) {
                    return;
                }
                ListSelectionModel rowSM = (ListSelectionModel) Ise.getSource();
                int selectedIndex = rowSM.getAnchorSelectionIndex();
                if (selectedIndex > -1) {
                    Qyteti q = qytetiTable.getQyteti(selectedIndex);
                    q.setEmriQytetit(q.getEmriQytetit());
                    q.setZipKodi(q.getZipKodi());

                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        savebtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        emriQytetittxt = new javax.swing.JTextField();
        zipkoditxt = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Qyteti");
        setMinimumSize(new java.awt.Dimension(700, 431));
        setPreferredSize(new java.awt.Dimension(700, 431));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        savebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        savebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/save.png"))); // NOI18N
        savebtn.setText("Ruaj");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        deletebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deletebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/delete.png"))); // NOI18N
        deletebtn.setText("Fshij");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        cancelbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/cancel.png"))); // NOI18N
        cancelbtn.setText("Anulo");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Zip Kodi: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 14, 77, 28));

        jLabel1.setText("Emri:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 141, 34));

        emriQytetittxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emriQytetittxtKeyTyped(evt);
            }
        });
        jPanel1.add(emriQytetittxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 51, 225, 40));

        zipkoditxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                zipkoditxtKeyTyped(evt);
            }
        });
        jPanel1.add(zipkoditxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 52, 220, 38));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        try {

            int row = tabela.getSelectedRow();
            if (emriQytetittxt.getText().equals("") || zipkoditxt.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Ju lutem plotesoni çdo fushë !!!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                if (row == -1) {
                    Qyteti qyteti = new Qyteti();
                    qyteti.setEmriQytetit(emriQytetittxt.getText());
                    qyteti.setZipKodi(Integer.parseInt(zipkoditxt.getText()));
                    qytetiR.create(qyteti);
                    JOptionPane.showMessageDialog(this, "E dhëna u ruajt me sukses !");
                } else {
                    Qyteti qyteti = new Qyteti();
                    qyteti.setEmriQytetit(emriQytetittxt.getText());
                    qyteti.setZipKodi(Integer.parseInt(zipkoditxt.getText()));            
                    qytetiR.create(qyteti);
                    JOptionPane.showMessageDialog(this, "E dhëna u editua me sukses !");
                }
                emptyObject();
                tabelaLoad();
            }

        } catch (QytetiException pe) {
            JOptionPane.showMessageDialog(this, pe.getMessage());
        } catch (Exception ex) {
            Logger.getLogger(AdministrataFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_savebtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        try {
            int row = tabela.getSelectedRow();
            if (row > -1) {
                Object[] ob = {"Po", "Jo"};
                int i = javax.swing.JOptionPane.showOptionDialog(this, "A dëshironi ta fshini ?", "Fshirja", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, null, ob, ob[1]);
                if (i == 0) {
                    Qyteti q = this.qytetiTable.getQyteti(row);
                    qytetiR.remove(q);
                    tabelaLoad();
                    emptyObject();
                    JOptionPane.showMessageDialog(this, "E dhëna është fshir me sukses !");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Nuk keni selektuar asgjë për të fshir !");
            }
        } catch (QytetiException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        tabela.clearSelection();
        emptyObject();
    }//GEN-LAST:event_cancelbtnActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        tabela.clearSelection();
    }//GEN-LAST:event_formMouseClicked

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        int row = tabela.getSelectedRow();
        if (row > -1) {
            Qyteti q = qytetiTable.getQyteti(row);
            emriQytetittxt.setText(q.getEmriQytetit());
            zipkoditxt.setText(""+q.getZipKodi());

        }
    }//GEN-LAST:event_tabelaMouseClicked

    private void emriQytetittxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emriQytetittxtKeyTyped
         char c = evt.getKeyChar();
        if (!((isAlphabetic((int) c)) || c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_SHIFT || c == KeyEvent.VK_SPACE)) {
            evt.consume();
        }
        String number =  emriQytetittxt.getText();
        if(number.length()>29){
            JOptionPane.showMessageDialog(this, "Keni tejakaluar numrin e lejuar te shkronjave(30)", "Gabim" , 0);
            evt.consume();
        }
    }//GEN-LAST:event_emriQytetittxtKeyTyped

    private void zipkoditxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zipkoditxtKeyTyped
          char c = evt.getKeyChar();
        if (!( c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_SHIFT || isDigit(c))) {
            evt.consume();
        }
        String number =  emriQytetittxt.getText();
        if(number.length()>4){
            JOptionPane.showMessageDialog(this, "Keni tejakaluar numrin e lejuar te numrave(5)", "Gabim" , 0);
            evt.consume();
        }
    }//GEN-LAST:event_zipkoditxtKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField emriQytetittxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton savebtn;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField zipkoditxt;
    // End of variables declaration//GEN-END:variables
}
